---
name: json_kit
description: Enhance Dart JSON manipulation with type safety, error-handling,
  and expressive extensions for seamless data handling.
version: 0.0.1
homepage: https://github.com/chaitanyabsprip/json_kit
repository: https://github.com/chaitanyabsprip/json_kit
issue_tracker: https://github.com/chaitanyabsprip/json_kit/issues

environment:
  sdk: ">=2.13.0 <4.0.0"

dev_dependencies:
  very_good_analysis: 5.1.0
