---
name: json_extensions
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/chaitanyabsprip/json_extensions
repository: https://github.com/chaitanyabsprip/json_extensions
issue_tracker: https://github.com/chaitanyabsprip/json_extensions/issues

environment:
  sdk: ">=2.13.0 <4.0.0"

dev_dependencies:
  very_good_analysis: 5.1.0
